// Navigation metadata stays independent of the lazily loaded demos.
export const componentCatalog = [
  { slug: "accordion", name: "Accordion" },
  { slug: "alert", name: "Alert" },
  { slug: "alert-dialog", name: "Alert Dialog" },
  { slug: "aspect-ratio", name: "Aspect Ratio" },
  { slug: "attachment", name: "Attachment" },
  { slug: "avatar", name: "Avatar" },
  { slug: "badge", name: "Badge" },
  { slug: "breadcrumb", name: "Breadcrumb" },
  { slug: "bubble", name: "Bubble" },
  { slug: "button", name: "Button" },
  { slug: "button-group", name: "Button Group" },
  { slug: "calendar", name: "Calendar" },
  { slug: "card", name: "Card" },
  { slug: "carousel", name: "Carousel" },
  { slug: "chart", name: "Chart" },
  { slug: "checkbox", name: "Checkbox" },
  { slug: "collapsible", name: "Collapsible" },
  { slug: "combobox", name: "Combobox" },
  { slug: "command", name: "Command" },
  { slug: "context-menu", name: "Context Menu" },
  { slug: "dialog", name: "Dialog" },
  { slug: "drawer", name: "Drawer" },
  { slug: "dropdown-menu", name: "Dropdown Menu" },
  { slug: "empty", name: "Empty" },
  { slug: "field", name: "Field" },
  { slug: "hover-card", name: "Hover Card" },
  { slug: "input", name: "Input" },
  { slug: "input-group", name: "Input Group" },
  { slug: "input-otp", name: "Input OTP" },
  { slug: "item", name: "Item" },
  { slug: "kbd", name: "Kbd" },
  { slug: "label", name: "Label" },
  { slug: "marker", name: "Marker" },
  { slug: "menubar", name: "Menubar" },
  { slug: "message", name: "Message" },
  { slug: "message-scroller", name: "Message Scroller" },
  { slug: "native-select", name: "Native Select" },
  { slug: "navigation-menu", name: "Navigation Menu" },
  { slug: "pagination", name: "Pagination" },
  { slug: "popover", name: "Popover" },
  { slug: "progress", name: "Progress" },
  { slug: "questionnaire", name: "Questionnaire" },
  { slug: "radio-group", name: "Radio Group" },
  { slug: "resizable", name: "Resizable" },
  { slug: "scroll-area", name: "Scroll Area" },
  { slug: "select", name: "Select" },
  { slug: "separator", name: "Separator" },
  { slug: "sheet", name: "Sheet" },
  { slug: "sidebar", name: "Sidebar" },
  { slug: "skeleton", name: "Skeleton" },
  { slug: "slider", name: "Slider" },
  { slug: "sonner", name: "Sonner" },
  { slug: "spinner", name: "Spinner" },
  { slug: "switch", name: "Switch" },
  { slug: "table", name: "Table" },
  { slug: "tabs", name: "Tabs" },
  { slug: "textarea", name: "Textarea" },
  { slug: "toast", name: "Toast" },
  { slug: "toggle", name: "Toggle" },
  { slug: "toggle-group", name: "Toggle Group" },
  { slug: "tooltip", name: "Tooltip" },
] as const;
